---
version: "3.5"
services:
  api:
    build:
      context: .
    stdin_open: true
    tty: true
    container_name: pca-api
    hostname: pca-api
    restart: on-failure
    links:
      - mongodb
    volumes:
      - ./src:/app
    env_file:
      - .env
    networks:
      - backend
    ports:
      - 8000:80
      - 8043:443

  mongodb:
    container_name: pca-mongodb
    hostname: mongodb
    image: "mongo:3.6"
    # These ports are exposed on the host; 'hostport:containerport'.
    # You could connect to this server from outside with the *host's*
    # DNS name or IP address and port 27017 (the left-hand side of the
    # colon).
    ports:
      - "27017:27017"
    volumes:
      # - ./etc/docker-entrypoint-initdb.d/001_users.js:/docker-entrypoint-initdb.d/001_users.js
      - "mongodb:/data/db"
    env_file:
      - .env
    networks:
      - backend

  browserless:
    image: browserless/chrome:latest
    container_name: pca-browserless
    environment:
      - "MAX_CONCURRENT_SESSIONS=10"
    ports:
      - "3000:3000"
    networks:
      - backend

# Host volumes used to store code.
volumes:
  mongodb:

networks:
  backend:
    name: pca_backend
