---
version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    container_name: pca-api
    hostname: pca-api
    restart: unless-stopped
    links:
      - mongodb
    volumes:
      - ./src:/var/www
    env_file:
      - .env
    ports:
      - 5000:5000
      - 8000:8000
      - 80:8000

  mongodb:
    container_name: pca-mongodb
    hostname: mongodb
    image: "mongo:4"
    restart: unless-stopped
    # These ports are exposed on the host; 'hostport:containerport'.
    # You could connect to this server from outside with the *host's*
    # DNS name or IP address and port 27017 (the left-hand side of the
    # colon).
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"
    env_file:
      - .env

# This can be enabled and disabled for testing reporting pdf generation
# browserless:
#   image: browserless/chrome:latest
#   container_name: pca-browserless
#   environment:
#     - "MAX_CONCURRENT_SESSIONS=10"
#   ports:
#     - "3000:3000"

# Host volumes used to store code.
volumes:
  mongodb:
