name: Deploy Dev

on:
  push:
    branches:
      - develop

jobs:
  dispatch:
    steps:
      - name: Env
        run: env
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CON_PCA_ACCESS_TOKEN }}
          repository: cisagov/con-pca
          event-type: deploy
          client-payload: '{"test": "test"}'
