name: Pull Request

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Set up pre-commit hook environments
        run: pre-commit install-hooks
      - name: pre-commit autoupdate
        run: pre-commit autoupdate
      - name: Run pre-commit on all files
        run: pre-commit run --all-files

  python_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Cache pip test requirements
        uses: actions/cache@v2
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: "${{ runner.os }}-pip-test-\
            ${{ hashFiles('**/requirements-test.txt') }}"
          restore-keys: |
            ${{ runner.os }}-pip-test-
            ${{ runner.os }}-pip-
      - name: Upgrade Pip
        run: python -m pip install --upgrade pip
      - name: Install Requirements
        run: pip install --upgrade --requirement requirements-test.txt
      - name: Copy env
        run: cp etc/env.dist .env
      - name: Pytest/Coverage
        run: |
          coverage run --omit *.venv*,*test* -m pytest ./tests/ --disable-warnings
          coverage report
