name: Terraform Apply

on:
    push:
        branches:
            - develop

jobs:
    terraform_apply:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 0.12.28

        - name: Verify Terraform version
          run: terraform --version

        - name: Terraform init
          working-directory: ./terraform
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: terraform init -input=false

        - name: Terraform validation
          working-directory: ./terraform
          run: terraform validate

        - name: Terraform plan
          working-directory: ./terraform
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: terraform plan -var="image_tag=1.9"
